# -*- coding: utf-8 -*-
"""p1_grouped

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MwZAMu6ZpaeyGcJ7XAXB0B0bHP8Fcrmq
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("old_cars.csv")
df

#Q1
#x mpg in discrete 3 segments 
#y is number of cars
#3 bars for each orgin (US,JAP, EU)
li =[]
for i in range(8,49,3):
  li.append(i)
df['bin'] =(pd.cut(df.MPG, bins=li))
gr = (df.groupby(by=[df.bin, df.Origin]).count())
gr =gr.reset_index()

bar = sns.barplot( x=gr.bin,y=gr.Model, hue=gr.Origin, palette='viridis' )
bar.set(xlabel="MPG Range", ylabel="Number of Cars" )
bar.set_title("Number or Cars vs MPG Range by Origin")
sns.set(rc={'figure.figsize':(20,8.27)})
