# -*- coding: utf-8 -*-
"""p1_line

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TyZuRDOQ27wWYZ-NIpupLvVX90JRJoUY
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("old_cars.csv")

#Q2
#evolution from gas milage from 1970 -1982
#Visualize for each production origin(Origin) the temporal evolution of the gas mileage from 1970 to 1982 using a line chart
#Each data point will correspond to the annual average of the gas mileage for a given origin 
#and each curve will comprise 13 points. Assign a different color to each curve 
#and plot all three curves in the same figure.

#3 lines
#x-axis: 1970-1982 (Model Year)
#y-axis: gas mileage

US = df[df.Origin=="US"].groupby(by=df.Model).mean()
Jap = df[df.Origin=="Japan"].groupby(by=df.Model).mean()
EU = df[df.Origin=="Europe"].groupby(by=df.Model).mean()

#df2= df.groupby(by=[df.Model, df.Origin]).mean()

plt.scatter(US.index,US.MPG)
plt.plot(US.index,US.MPG)
plt.scatter(Jap.index,Jap.MPG)
plt.plot(Jap.index,Jap.MPG)
plt.scatter(EU.index,EU.MPG)
plt.plot(EU.index,EU.MPG)
plt.legend(['US', 'Japan', 'EU'])
plt.xlabel("Model Year")
plt.ylabel("Gas Mileage")
plt.title("Evolution of Gas Milage From 1970 - 1982")
plt.show()

