# -*- coding: utf-8 -*-
"""p1_scatter

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pi2RRU1vwcsnO4iOsjDLCA_AxhQrzDmz
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("old_cars.csv")

#Q3
# relationship between horsepower and gas mileage in a scatter plot. 
#The horizontal axis should correspond to ‘Horsepower’, 
#the vertical axis to ‘MPG’ and each data point to a particular car. 
#Apply to the scatter plot a color coding indicating the 'Year'.
# Use for that purpose the color palette Viridis

#x horsepower
#y ‘MPG’ and each data point to a particular car
#plt.scatter(x=df.Horsepower, y=df.MPG)

scat = sns.scatterplot(x=df.Horsepower, y=df.MPG, hue=df.Model, palette='viridis')
scat.legend(title='Year')
scat.set_title("Horsepower vs Mileage")
